# This file was generated by GoReleaser. DO NOT EDIT.
class Armada < Formula
  desc "A multi-cluster batch queuing system for high-throughput workloads on Kubernetes."
  homepage "https://armadaproject.io/"
  version "0.1.14"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/stackedsax/armada/releases/download/v0.1.14/armada_0.1.14_Darwin_x86_64.tar.gz"
    sha256 "436e6f9b224d1ed5bbc4663e90e35ecd7f84331a21869cd4593d036970cd4647"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/stackedsax/armada/releases/download/v0.1.14/armada_0.1.14_Linux_x86_64.tar.gz"
      sha256 "19f240b3fd617954413250641a5be941784565c0c0c382e7f994f4d021d862af"
    end
  end

  def install
    bin.install "armada"
  end
end
