# This file was generated by GoReleaser. DO NOT EDIT.
class Armada < Formula
  desc "A multi-cluster batch queuing system for high-throughput workloads on Kubernetes."
  homepage "https://armadaproject.io/"
  version "0.1.15"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/stackedsax/armada/releases/download/v0.1.15/armada_0.1.15_Darwin_x86_64.tar.gz"
    sha256 "64e1648b511ae4fcae57bcbed6af956a72f8cf19db7d4fbe0d51e6a7a1657eb4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/stackedsax/armada/releases/download/v0.1.15/armada_0.1.15_Linux_x86_64.tar.gz"
      sha256 "0a9557670774aaf41ab666580c8ebbd86da3d27740639ce5dd46958048712cd9"
    end
  end

  def install
    bin.install "armadactl"
  end
end
